sudo: required
services:
  - docker

before_install: 
  - docker build -t worklifetech/docker-reat-test -f ./client/Dockerfile.dev ././client/Dockerfile.dev

script:
  - docker run -e CI=true  worklifetech/docker-reat-test npm test

after_success: 
  - docker build -t worklifetech/multi-client ./client
  - docker build -t worklifetech/multi-nginx ./nginx
  - docker build -t worklifetech/multi-server ./server
  - docker build -t worklifetech/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push worklifetech/multi-client
  - docker push worklifetech/multi-nginx
  - docker push worklifetech/multi-server
  - docker push worklifetech/multi-worker